[build]
  command = "bun nx run ai-content-generator:build"
  publish = "/apps/ai-content-generator/.next"

[context.production]
  ignore = "echo $NETLIFY_TRIGGERED_BY_HOOK | grep -q 'false' && exit 0 || exit 1"
