[build]
  command = "bun nx run ai-content-generator:build"
  publish = "/apps/ai-content-generator/.next"

[build.environment]
  # Control build trigger
  DEPLOY_TRIGGERED_BY_HOOK = "false"
  
[context.production]
  ignore = "echo $DEPLOY_TRIGGERED_BY_HOOK | grep -q 'false' && exit 0 || exit 1"

[context.deploy-preview]
  ignore = "echo $DEPLOY_TRIGGERED_BY_HOOK | grep -q 'false' && exit 0 || exit 1"
