[build]
  command = "bun nx run banking:build"
  publish = "/apps/banking/.next"

[build.environment]
  # Control build trigger
  NETLIFY_TRIGGERED_BY_HOOK = "false"

[context.production]
  ignore = "echo $NETLIFY_TRIGGERED_BY_HOOK | grep -q 'false' && exit 0 || exit 1"

[context.deploy-preview]
  ignore = "echo $NETLIFY_TRIGGERED_BY_HOOK | grep -q 'false' && exit 0 || exit 1"