name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --no-cache
      - name: 'Derive approperiate SHAs for base and head for `nx affected` commands'
        uses: nrwl/nx-set-shas@v4
      - run: bun nx affected -t lint
  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --no-cache
      - name: 'Derive approperiate SHAs for base and head for `nx affected` commands'
        uses: nrwl/nx-set-shas@v4
      - run: bun nx affected -t test
  build:
    name: Run Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --no-cache
      - name: 'Derive approperiate SHAs for base and head for `nx affected` commands'
        uses: nrwl/nx-set-shas@v4
      - run: bun nx affected -t build
