name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download bun
        uses: oven-sh/setup-bun@v1
        with: 
          bun-version: 0
      - run: bunx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      - name: Install dependencies
        run: bun install --no-cache
      - name: 'Derive approperiate SHAs for base and head for `nx affected` commands'
        uses: nrwl/nx-set-shas@v4
      - run: bun nx affected -t lint
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download bun
        uses: oven-sh/setup-bun@v1
        with: 
          bun-version: 0
      - run: bunx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      - name: Install dependencies
        run: bun install --no-cache
      - name: 'Derive approperiate SHAs for base and head for `nx affected` commands'
        uses: nrwl/nx-set-shas@v4
      - run: bun nx affected -t test 
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  build:
    name: Run Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download bun
        uses: oven-sh/setup-bun@v1
        with: 
          bun-version: 0
      - run: bunx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      - name: Install dependencies
        run: bun install --no-cache
      - name: 'Derive approperiate SHAs for base and head for `nx affected` commands'
        uses: nrwl/nx-set-shas@v4
      - run: bun nx affected -t build
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}